---
base_url: http://my-card.in/roid
zh:
  size: 1996800
  upgrade_url: http://my-card.in/roid/zh/cards-2013-8-27.cdb
  count: 6234
en:
  size: 2158592
  upgrade_url: http://my-card.in/roid/zh/cards.cdb
  count: 6234
