datas:
  id: _id
  ot: ot
  alias: alias
  setcode: setcode
  type: type
  atk: atk
  def: def
  level: level
  race: race
  attribute: attribute
  category: category

texts:
  id: _id
  name: name
  desc: desc
  str1: str1
  str2: str2
  str3: str3
  str4: str4
  str5: str5
  str6: str6
  str7: str7
  str8: str8
  str9: str9
  str10: str10
  str11: str11
  str12: str12
  str13: str13
  str14: str14
  str15: str15
  str16: str16

