version: &base
  latest_version: '1.25'
  upgrade_url: http://my-card.in/roid/latest/MC_YGORoid.apk

zh:
  <<: *base
  desc: 1. 增加自动更新数据库的开关。\n2. 优化内存使用。

en:
  <<: *base
  desc: 1. Add a feture toggle for auto upgrade database.\n2. Optimize memory use.

jp:
  <<: *base
  desc: 1. カード情報自動更新のスイーチを増加する。\n2. メモリーの使用を優化する。

zh-TW:
  <<: *base
  desc: 1. 增加自動更新數據庫的開關。\n2. 優化內存使用。
