version: &base
  latest_version: '1.20'
  upgrade_url: http://112.124.4.110:8080/YGORoid_1.20.apk

zh:
  <<: *base
  desc: 1. 增加简易反口胡卡查。\n2. 增加组卡器功能。

en:
  <<: *base
  desc: 1. Add a card searcher.\n2. Add a deck builder.
