version: &base
  latest_version: '1.31'
  upgrade_url: http://my-card.in/roid/latest/MC_YGORoid.apk

zh:
  <<: *base
  desc: 1. 修正换龙族。\n2. 修正灵摆怪兽等级。

en:
  <<: *base
  desc: 1. Fix WYRMS.\n2. Fix level of p-monster.

jp:
  <<: *base
  desc: 1. 幻竜を修正。\n2. Pモンスターを修正。

zh-TW:
  <<: *base
  desc: 1. 修正幻龍族。\n2. 修正擺動怪獸等級。
