version: &base
  latest_version: '1.30'
  upgrade_url: http://my-card.in/roid/latest/MC_YGORoid.apk

zh:
  <<: *base
  desc: 1. 修改场地布局，新增摇摆区。\n2. 更好用的双人LP计算器。

en:
  <<: *base
  desc: 1. Change the duel fields, add the p-zone.\n2. New LP calculator for two player.

jp:
  <<: *base
  desc: 1. あたらしいフールド、Pゾーンを増加する。\n2. 二人用のLPカルキュレーター。

zh-TW:
  <<: *base
  desc: 1. 修改場地佈局，新增搖擺區。\n2. 更好用的雙人LP計算器。
